version: "3.1"

services:
    mysql:
      image: mysql:5.7
      container_name: csv-convert-app-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=test
        - MYSQL_USER=appdev
        - MYSQL_PASSWORD=apppass
      ports:
        - "8102:3306"

    webserver:
      image: nginx:alpine
      container_name: csv-convert-app-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8100:80"

    php-fpm:
      build: docker/php-fpm
      container_name: csv-convert-app-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
